default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres
  host: localhost

development:
  <<: *default
  database: weight_tracker1_development
test:
  <<: *default
  database: weight_tracker1_test
production:
  <<: *default
  database: weight_tracker1_production
